name: CI-macOS.yml

on: push

env:
  DEVELOPER_DIR: /Applications/Xcode_12.4.app

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Build and Test
      run: |
        xcodebuild clean build test -project EssentialFeed.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -sdk macosx -destination "platform=macOS" ONLY_ACTIVE_ARCH=YES
